services:
  detector: 
    image: detector
    user: root
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - NVIDIA_DISABLE_REQUIRE=1
      - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:${LD_LIBRARY_PATH}
    build: .
    container_name: detector
    ports:
      - "8003:8000"
    volumes:
      - .:/app